from typing import Protocol, runtime_checkable

import threading
from collections.abc import Callable

from tidalapi.session import Session

from tidal_dl_ng.model.cfg import Settings as ModelSettings
from tidal_dl_ng.model.cfg import Token as ModelToken

@runtime_checkable
class JsonSerializable(Protocol):
    def to_json(self, *args: object, **kwargs: object) -> str: ...
    @classmethod
    def from_json(
        cls, *args: object, **kwargs: object
    ) -> JsonSerializable: ...

class BaseConfig[T]:
    data: T
    file_path: str
    cls_model: type[T]
    path_base: str

    def save(self, config_to_compare: str | None = None) -> None: ...
    def set_option(self, key: str, value: object) -> None: ...
    def read(self, path: str) -> bool: ...

class Settings(BaseConfig[ModelSettings]):
    def __init__(self) -> None: ...

class Tidal(BaseConfig[ModelToken]):
    session: Session
    token_from_storage: bool
    settings: Settings
    is_pkce: bool

    def __init__(self, settings: Settings | None = None) -> None: ...
    def login(self, fn_print: Callable[[str], None]) -> bool: ...
    def login_token(self, do_pkce: bool | None = None) -> bool: ...
    def login_finalize(self) -> bool: ...
    def login_hifi_api(self, fn_print: Callable[[str], None]) -> bool: ...
    def finalize_and_enable_hires(self) -> bool: ...
    def verify_lossless_capability(self) -> bool: ...
    def logout(self) -> bool: ...
    def settings_apply(self, settings: Settings | None = None) -> bool: ...

class HandlingApp:  # pylint: disable=too-few-public-methods
    event_abort: threading.Event
    event_run: threading.Event

    def __init__(self) -> None: ...
