site_name: tidal-dl-ng
repo_url: https://github.com/FunWarry/tidal-dl-ng-For-DJ
site_url: https://exislow.github.io/tidal-dl-ng
site_description: TIDAL Media Downloader Next Generation!
site_author: Robert Honz
edit_uri: edit/main/docs/
repo_name: FunWarry/tidal-dl-ng-For-DJ
copyright: Maintained by <a href="https://example.com">Robby</a>.

nav:
  - Home: index.md
  - Modules: modules.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_root_heading: true
            show_source: true
            docstring_style: google

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FunWarry/tidal-dl-ng-For-DJ
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/tidal-dl-ng

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
