from collections.abc import Callable
from typing import TypeVar, TypeAlias

_T = TypeVar("_T")
_KwargsType: TypeAlias = dict[str, object]

class FFmpeg:
    def __init__(self, executable: str | None = None) -> None: ...
    def option(self, *options: str) -> FFmpeg: ...
    def input(self, video_url: str, **kwargs: object) -> FFmpeg: ...
    def output(self, video_url: str, **kwargs: object) -> FFmpeg: ...
    def execute(
        self,
        encoding: str = "utf-8",
        callbacks: Callable[..., object] | None = None,
    ) -> str: ...
    def terminate(self) -> None: ...
    def emit(self, event_name: str, *args: object) -> None: ...
    def on(
        self, event_name: str, callback: Callable[..., object]
    ) -> FFmpeg: ...
    def once(
        self, event_name: str, callback: Callable[..., object]
    ) -> FFmpeg: ...
    def listeners(self, event_name: str) -> list[Callable[..., object]]: ...
    def add_listener(
        self, event_name: str, callback: Callable[..., object]
    ) -> None: ...
    def remove_listener(
        self, event_name: str, callback: Callable[..., object]
    ) -> None: ...
    def remove_all_listeners(self, event_name: str | None = None) -> None: ...
    def listens_to(
        self, event_name: str
    ) -> Callable[[Callable[..., _T]], Callable[..., _T]]: ...
    def arguments(self) -> list[str]: ...
