"""Type stubs for the `ffmpeg-python` package (imported as `ffmpeg`).

The upstream package ships no type information, so this minimal stub
describes only the surface used by `tidal_dl_ng.download`.
"""

from typing import Any

class FFmpeg:
    """Thin wrapper around an `ffmpeg` command-line invocation."""

    def __init__(self, executable: str | None = ...) -> None: ...
    def option(self, *options: str) -> "FFmpeg": ...
    def input(
        self,
        video_url: str,
        **kwargs: Any,
    ) -> "FFmpeg": ...
    def output(
        self,
        video_url: str,
        **kwargs: Any,
    ) -> "FFmpeg": ...
    def execute(
        self,
        encoding: str = ...,
        callbacks: Any = ...,
    ) -> str: ...
    def termininate(self) -> None: ...
    def emit(self, event_name: str, *args: Any) -> None: ...
    def on(self, event_name: str, callback: Any) -> "FFmpeg": ...
    def once(self, event_name: str, callback: Any) -> "FFmpeg": ...
    def listeners(self, event_name: str) -> list[Any]: ...
    def add_listener(self, event_name: str, callback: Any) -> None: ...
    def remove_listener(self, event_name: str, callback: Any) -> None: ...
    def remove_all_listeners(self, event_name: str | None = ...) -> None: ...
    def listens_to(self, event_name: str) -> Any: ...
    def arguments(self) -> list[str]: ...
