from pathlib import Path

from mutagen import FileType, MutagenError
from mutagen._vorbis import VCommentDict

class FLACNoHeaderError(MutagenError): ...
class FLACVorbisError(MutagenError): ...

class Picture:
    type: int
    data: bytes
    mime: str
    code: int
    def __init__(self) -> None: ...
    def load(self, fileobj: object) -> None: ...
    def write(self, fileobj: object) -> None: ...

class VCFLACDict(VCommentDict):
    code: int
    def load(
        self, fileobj: bytes, errors: str = "strict", framing: bool = True
    ) -> None: ...
    def write(self, framing: bool = True) -> bytes: ...

class FLAC(FileType):
    @property
    def tags(self) -> VCFLACDict | None: ...
    metadata_blocks: list[object]
    def add_tags(self) -> None: ...
    def clear_pictures(self) -> None: ...
    def add_picture(self, picture: Picture) -> None: ...
    def save(
        self,
        filething: str | Path | None = None,
        deleteid3: bool = False,
        padding: object = None,
        **kwargs: object,
    ) -> None: ...
