"""Stub for mutagen.flac."""

from mutagen._vorbis import VCommentDict
from mutagen import FileType, MutagenError

class FLACNoHeaderError(MutagenError): ...
class FLACVorbisError(MutagenError): ...

class Picture:
    type: int
    data: bytes
    mime: str
    def __init__(self) -> None: ...

class VCFLACDict(VCommentDict):
    code: int
    def load(
        self, data: bytes, errors: str = ..., framing: bool = ...
    ) -> None: ...
    def write(self, framing: bool = ...) -> bytes: ...

class FLAC(FileType):
    tags: VCFLACDict | None
    metadata_blocks: list[object]
    def add_tags(self) -> None: ...
    def clear_pictures(self) -> None: ...
    def add_picture(self, picture: Picture) -> None: ...
    def save(  # noqa: E501
        self, filename: str | None = ..., padding: object = ...
    ) -> None: ...
