from mutagen._vorbis import VCommentDict
from mutagen import FileType, MutagenError
from pathlib import Path

class FLACNoHeaderError(MutagenError): ...
class FLACVorbisError(MutagenError): ...

class Picture:
    type: int
    data: bytes
    mime: str
    def __init__(self) -> None: ...

class VCFLACDict(VCommentDict):
    code: int
    def load(
        self, data: bytes, errors: str = "strict", framing: bool = True
    ) -> None: ...
    def write(self, framing: bool = True) -> bytes: ...

class FLAC(FileType):
    tags: VCFLACDict
    metadata_blocks: list[object]
    def add_tags(self) -> None: ...
    def clear_pictures(self) -> None: ...
    def add_picture(self, picture: Picture) -> None: ...
    def save(
        self, filename: str | Path | None = None, padding: object = None
    ) -> None: ...
