from collections.abc import Iterator

class VCommentDict:
    def __setitem__(self, key: str, value: str | list[str]) -> None: ...
    def __getitem__(self, key: str) -> list[str]: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[tuple[str, str]]: ...
    def keys(self) -> list[str]: ...
    def pop(self, key: str, default: str | None = ...) -> str | None: ...
