from collections.abc import Iterator

class VCommentDict:
    def __init__(
        self,
        data: object = None,
        *args: object,
        **kwargs: object,
    ) -> None: ...
    def __setitem__(self, key: str, value: str | list[str]) -> None: ...
    def __getitem__(self, key: str) -> list[str]: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[tuple[str, str]]: ...
    def keys(self) -> list[str]: ...
    def get(self, key: str, default: str | None = None) -> str | None: ...
    def items(self) -> list[tuple[str, list[str]]]: ...
    def values(self) -> list[list[str]]: ...
    def as_dict(self) -> dict[str, list[str]]: ...
    def load(
        self,
        fileobj: object,
        errors: str = "replace",
        framing: bool = True,
    ) -> None: ...
    def write(self, framing: bool = True) -> bytes: ...
