from dataclasses import dataclass

from dataclasses_json import DataClassJsonMixin
from tidalapi.media import Quality

from tidal_dl_ng.constants import (
    CoverDimensions,
    MetadataTargetUPC,
    QualityVideo,
)

@dataclass
class Settings(DataClassJsonMixin):
    lyrics_embed: bool
    lyrics_file: bool
    use_primary_album_artist: bool
    video_download: bool
    skip_existing: bool
    download_delay: bool
    download_base_path: str
    quality_audio: Quality
    quality_video: QualityVideo
    download_dolby_atmos: bool
    format_album: str
    format_playlist: str
    format_mix: str
    format_track: str
    format_video: str
    video_convert_mp4: bool
    path_binary_ffmpeg: str
    metadata_cover_dimension: CoverDimensions
    metadata_cover_embed: bool
    mark_explicit: bool
    cover_album_file: bool
    extract_flac: bool
    downloads_simultaneous_per_track_max: int
    download_delay_sec_min: float
    download_delay_sec_max: float
    album_track_num_pad_min: int
    downloads_concurrent_max: int
    symlink_to_track: bool
    playlist_create: bool
    metadata_replay_gain: bool
    metadata_write_url: bool
    window_x: int
    window_y: int
    window_w: int
    window_h: int
    metadata_delimiter_artist: str
    metadata_delimiter_album_artist: str
    filename_delimiter_artist: str
    filename_delimiter_album_artist: str
    metadata_target_upc: MetadataTargetUPC
    api_rate_limit_batch_size: int
    api_rate_limit_delay_sec: float

    def to_dict(self, encode_json: bool = False) -> dict[str, object]: ...

@dataclass
class HelpSettings(DataClassJsonMixin):
    skip_existing: str = ...
    album_cover_save: str = ...
    lyrics_embed: str = ...
    use_primary_album_artist: str = ...
    lyrics_file: str = ...
    video_download: str = ...
    download_delay: str = ...
    download_base_path: str = ...
    quality_audio: str = ...
    quality_video: str = ...
    download_dolby_atmos: str = ...
    format_album: str = ...
    format_playlist: str = ...
    format_mix: str = ...
    format_track: str = ...
    format_video: str = ...
    video_convert_mp4: str = ...
    path_binary_ffmpeg: str = ...
    metadata_cover_dimension: str = ...
    metadata_cover_embed: str = ...
    mark_explicit: str = ...
    cover_album_file: str = ...
    extract_flac: str = ...
    downloads_simultaneous_per_track_max: str = ...
    download_delay_sec_min: str = ...
    download_delay_sec_max: str = ...
    album_track_num_pad_min: str = ...
    downloads_concurrent_max: str = ...
    symlink_to_track: str = ...
    playlist_create: str = ...
    metadata_replay_gain: str = ...
    metadata_write_url: str = ...
    window_x: str = ...
    window_y: str = ...
    window_w: str = ...
    window_h: str = ...
    metadata_delimiter_artist: str = ...
    metadata_delimiter_album_artist: str = ...
    filename_delimiter_artist: str = ...
    filename_delimiter_album_artist: str = ...
    metadata_target_upc: str = ...
    api_rate_limit_batch_size: str = ...
    api_rate_limit_delay_sec: str = ...

    def to_dict(self, encode_json: bool = False) -> dict[str, str]: ...
