"""Stub for tidalapi.artist with resolved forward references."""

from enum import Enum
from typing import List, Optional

from tidalapi.media import Album, Mix, Playlist, Track, Video

class Role(Enum):
    """Artist role enumeration."""

    main: "Role" = "main"
    featured: "Role" = "featured"
    artist: "Role" = "artist"
    contributor: "Role" = "contributor"

class Artist:
    """A TIDAL artist."""

    id: object
    name: str
    roles: Optional[List[Role]]

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def get_albums(
        self, limit: int = ..., offset: int = ...
    ) -> List[Album]: ...
    def get_ep_singles(
        self, limit: int = ..., offset: int = ...
    ) -> List[Album]: ...
    def get_mixes(self, limit: int = ..., offset: int = ...) -> List[Mix]: ...
    def get_top_tracks(
        self, limit: int = ..., offset: int = ...
    ) -> List[Track]: ...
    def get_videos(
        self, limit: int = ..., offset: int = ...
    ) -> List[Video]: ...
    def get_bio(self) -> object: ...
    def get_playlists(self) -> List[Playlist]: ...
